version: '3'

services:
  database:
    image: mysql:latest
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_nfq
    ports:
      - '3306:3306'
    volumes:
      - ./database:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/html
    links:
      - database

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./public:/var/www/html/public
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    links:
      - database
      - php
volumes:
  ###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
